docs: application section updated to v2
cartesi/docs pull request #239
Opened 2024-12-02 09:45 UTC by henriquemarlon

2025-03-04 15:17 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +The **Application** contract acts as the base layer incarnation of a application running on the execution layer. The application can interact with other smart contracts through the execution an valid
Typo: Should be execution and validation, not *an validation

2025-03-04 15:18 UTC, riseandshaheen requested changes

2025-03-04 15:18 UTC, riseandshaheen commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +A output was executed from the Application, this event is emitted when a output is executed so it must be triggered on a successful call to [executeOutput](#executeOutput).
An output...

2025-03-04 15:26 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +Every Application is subscribed to a consensus contract and governed by a single address, the owner. The consensus has the power to submit claims, which, in turn, are used to validate outputs. The ow
I think it's a good idea to let users know that based on centralization/ ownership concerns, it's possible to change the ownership model and this is handled under the consensus contract and also point them to the IConsensus page for more consensus models.

2025-03-04 15:51 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +Try to execute a output.
Typo: This should be [Try to execute an output]

2025-03-04 15:51 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +Validate a output.
Typo: Should be [Validate an output]

2025-03-04 15:51 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/input-box.md
> +The **InputBox** is a trustless and permissionless contract that receives arbitrary blobs (called "inputs") from anyone and adds a compound hash to an append-only list (called "input box"). Each appl
I think it's a bit misleading to say each application has its input box, while in reality all applications on Cartesi share the same input box

2025-03-08 02:27 UTC, henriquemarlon commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/input-box.md
> +The **InputBox** is a trustless and permissionless contract that receives arbitrary blobs (called "inputs") from anyone and adds a compound hash to an append-only list (called "input box"). Each appl
You are absolutely right; that went unnoticed in my review when I replaced the term "dApp" with "application," since it was already in the previous version.

2025-03-08 02:37 UTC, henriquemarlon commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +Every Application is subscribed to a consensus contract and governed by a single address, the owner. The consensus has the power to submit claims, which, in turn, are used to validate outputs. The ow
What do you think about this @Nonnyjoe:

"Every Application is subscribed to a consensus contract and governed by a single address, the owner. The consensus has the power to submit claims, which, in turn, are used to validate outputs. The owner has complete power over the Application, as it can replace the consensus at any time. Therefore, the users of an Application must trust both the consensus and the application owner. It is important to note that, depending on centralization or ownership concerns, it is possible to change the ownership model. This process is managed under the consensus contract. For more information about different ownership and consensus models, refer to the [IConsensus](https://github.com/cartesi/rollups-contracts/blob/prerelease/2.0.0/contracts/consensus/IConsensus.sol)."

2025-03-08 07:45 UTC, Nonnyjoe commented on cartesi-rollups_versioned_docs/version-2.0/api-reference/json-rpc/application.md
> +Every Application is subscribed to a consensus contract and governed by a single address, the owner. The consensus has the power to submit claims, which, in turn, are used to validate outputs. The ow
Yeahh... This looks good @henriquemarlon

2025-03-10 16:42 UTC, Nonnyjoe approved these changes

2025-03-11 13:26 UTC, merged