Improved UX based on user feedback
cartesi/docs pull request #71
Opened 2023-07-30 20:55 UTC by nicocartesi

Based on multiple feedback sessions, it was pointed out that the landing page needs to direct readers to the required section. Furthermore, for new readers, it is not clear what Cartesi exactly entails.

This PR aims to:

- Provide a short description of Cartesi for a better understanding of Cartesi Framework
- Provide a shortcut to the required information, especially to the hands-on part on building DApps

2023-08-03 10:48 UTC, nicocartesi commented
Hi @dimitarangelkov , can you please review this PR from the UX perspective? Thanks!

2023-08-03 14:40 UTC, felipeargento commented
Hello!

To be honest, I didn't like this description very much. The text, as it stands, appears to be repetitive in some places, and somewhat confusing in others. There are also some grammar mistakes and inconsistencies.  For instance, "Cartesi Rollups ecosystem" should be "The Cartesi Rollups ecosystem" to be grammatically correct. In addition, the capitalization of "DApps" is inconsistent, appearing as "Dapps" later in the text.

I'd consider reworking the description around the three phrases found on the cartesi.io website. They are concise, easy to understand, and accurately represent what Cartesi offers:

1) "Application-specific rollups with a Linux runtime."

2) "Cartesi gives your DApp its own rollup with a dedicated CPU, bringing significant gains in computational scalability without compromising on decentralization, security and censorship resistance."

3) "With the Cartesi Virtual Machine, DApp developers move beyond the EVM and gain access to the full suite of code libraries, programming languages, and open-source tooling they're accustomed to."

2023-08-04 16:14 UTC, dimitarangelkov commented
@nicocartesi I'll fine tune the two buttons styles, to match the branding guide lines etc. Other than that, the text under the main headline is a bit too long for that part of the screen. Nobody wants to read long sentences.

2023-08-04 16:26 UTC, dimitarangelkov commented on src/components/Hello.js
> +  };
```
const buttonStyle = {
    padding: "0.75rem 0.75rem",
    textAlign: "center",
    textDecoration: "none",
    backgroundColor: "#1B1A1E",
    color: "#fff",
    borderRadius: "0.25rem",
    fontWeight: "bold",
    textTransform: "uppercase",
    width: "100%",
  };

  const buttonContainerStyle = {
    display: "flex",
    justifyContent: "center",
    gap: "0.75rem",
    marginTop: "1.5rem",
  };
```

2023-08-04 16:27 UTC, dimitarangelkov commented on src/components/Hello.js
> +  };
@nicocartesi here are the updated styles

2023-08-04 16:28 UTC, dimitarangelkov requested changes
Added a comment with the updated styles

2023-08-04 16:42 UTC, nicocartesi commented
Thanks @felipeargento and @dimitarangelkov for the feedback! I have amended the text in line with @felipeargento 's suggestion but shortened it a bit as per @dimitarangelkov 's suggestion. Added the button styles too:
<img width="1440" alt="Screenshot 2023-08-04 at 17 39 06" src="https://github.com/cartesi/docs/assets/122233130/e6b15dd4-8eb0-432b-a1a0-0d9276c52d87">

Please let me know if this version is good to go. Thanks!

2023-08-04 17:36 UTC, dimitarangelkov approved these changes
lgtm!

2023-08-08 17:58 UTC, merged